# Generated by Django 2.1.7 on 2019-02-15 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_create_providers_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('created', 'name')},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('date_joined',)},
        ),
        migrations.AddField(
            model_name='area',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
